package top.apower.sqldemo.mapper.data;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import top.apower.sqldemo.model.data.ActorFilmDO;
import top.apower.sqldemo.model.data.ActorFilmDOExample;

public interface ActorFilmDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor_film
     *
     * @mbg.generated
     */
    long countByExample(ActorFilmDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor_film
     *
     * @mbg.generated
     */
    int deleteByExample(ActorFilmDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor_film
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor_film
     *
     * @mbg.generated
     */
    int insert(ActorFilmDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor_film
     *
     * @mbg.generated
     */
    int insertSelective(ActorFilmDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor_film
     *
     * @mbg.generated
     */
    List<ActorFilmDO> selectByExample(ActorFilmDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor_film
     *
     * @mbg.generated
     */
    ActorFilmDO selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor_film
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ActorFilmDO record, @Param("example") ActorFilmDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor_film
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ActorFilmDO record, @Param("example") ActorFilmDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor_film
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ActorFilmDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor_film
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ActorFilmDO record);
}