package top.apower.sqldemo.mapper.data;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import top.apower.sqldemo.model.data.ActorDO;
import top.apower.sqldemo.model.data.ActorDOExample;

public interface ActorDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor
     *
     * @mbg.generated
     */
    long countByExample(ActorDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor
     *
     * @mbg.generated
     */
    int deleteByExample(ActorDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor
     *
     * @mbg.generated
     */
    int insert(ActorDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor
     *
     * @mbg.generated
     */
    int insertSelective(ActorDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor
     *
     * @mbg.generated
     */
    List<ActorDO> selectByExample(ActorDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor
     *
     * @mbg.generated
     */
    ActorDO selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ActorDO record, @Param("example") ActorDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ActorDO record, @Param("example") ActorDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ActorDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ActorDO record);
}