package top.apower.sqldemo.mapper.data;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import top.apower.sqldemo.model.data.FilmDO;
import top.apower.sqldemo.model.data.FilmDOExample;

public interface FilmDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbg.generated
     */
    long countByExample(FilmDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbg.generated
     */
    int deleteByExample(FilmDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbg.generated
     */
    int insert(FilmDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbg.generated
     */
    int insertSelective(FilmDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbg.generated
     */
    List<FilmDO> selectByExample(FilmDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbg.generated
     */
    FilmDO selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FilmDO record, @Param("example") FilmDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FilmDO record, @Param("example") FilmDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FilmDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FilmDO record);
}